baseURL = "http://localhost/"
enableRobotsTXT = true
languageCode = "en-us"
theme = "lilac-revenge"
title = "Friends of DramaTech"
buildDrafts = true

[markup.goldmark.renderer]
unsafe = true

[params]

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true