name: Publish Staging
on:
  push:
    branches:
      - staging
jobs:
  publish-hugo:
    runs-on: ubuntu-latest
    env:
      HUGO_ENV: staging
    steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.STAGING_DEPLOYMENT_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.STAGING_DEPLOYMENT_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
            role-to-assume: ${{ secrets.STAGING_DEPLOYMENT_ROLE_ARN }}
            role-duration-seconds: 1200
            role-session-name: StagingHugoPublisherWorkflow
        - uses: actions/checkout@v4
          with:
            submodules: true 
            fetch-depth: 0
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: latest
            extended: true
        - name: Install Node
          uses: actions/setup-node@v4
        - name: Cache Deps
          uses: actions/cache@v4
          with:
             key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
             path: node_modules
        - name: Install Deps
          run: npm ci
        - name: Build Tina
          run: npx tinacms build
          env:
            NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.TINA_CMS_CLIENT_ID }}
            TINA_TOKEN: ${{ secrets.TINA_CMS_RO_TOKEN }}
        - name: Build Hugo
          run:  hugo --verbose
        - name: Deploy
          run: hugo deploy --verbose
