name: Publish Mainline
on:
  push:
    branches:
      - mainline
jobs:
  publish-hugo:
    runs-on: ubuntu-latest
    steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.PROD_DEPLOYMENT_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.PROD_DEPLOYMENT_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
            role-to-assume: ${{ secrets.PROD_DEPLOYMENT_ROLE_ARN }}
            role-duration-seconds: 1200
            role-session-name: ProdHugoPublisherWorkflow
        - uses: actions/checkout@v2
          with:
            submodules: true 
            fetch-depth: 0
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: '0.79.0'
            extended: true
        - name: Build
          run: hugo --verbose
        - name: Deploy
          run: hugo deploy --verbose
